# Generated by Django 5.1.2 on 2024-10-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content_preferences',
            new_name='preferences',
        ),
    ]
