# Generated by Django 5.1.2 on 2024-10-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_content_preferences_profile_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='authentication.preference'),
        ),
    ]
