# Generated by Django 5.1.2 on 2024-10-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_preference_remove_profile_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(default=list),
        ),
    ]
