# Generated by Django 5.1.2 on 2024-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_profile_preferences_delete_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPrefrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefrences', models.CharField(max_length=250)),
            ],
        ),
    ]
