# Generated by Django 5.1.2 on 2024-10-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_contentprefrences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentprefrences',
            old_name='prefrences',
            new_name='name',
        ),
    ]
