# Generated by Django 5.1.2 on 2024-10-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_prefrences_contentprefrences_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(default=list, to='authentication.contentprefrences'),
        ),
    ]
