# Generated by Django 5.1.2 on 2024-10-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_profile_preferences_profile_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedPrefrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(default=list, to='authentication.selectedprefrence'),
        ),
    ]
