# Generated by Django 5.1.2 on 2024-10-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_preferences_profile_preferences1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferences5',
        ),
    ]
