# Generated by Django 5.1.2 on 2024-10-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_profile_preferences4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preferences1',
            new_name='preference1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='preferences2',
            new_name='preference2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='preferences3',
            new_name='preference3',
        ),
    ]
