# Generated by Django 5.1.2 on 2024-10-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_profile_preference1_alter_profile_preference2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
