# Generated by Django 5.1.2 on 2024-10-18 01:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cateory',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
            preserve_default=False,
        ),
    ]
