# Generated by Django 5.1.2 on 2024-10-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_cateory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cateory',
            new_name='category',
        ),
    ]
